### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-saramarin23#1]
Buen trabajo @saramarin23  !

Algunas pistas para acabarlo:

- [x] Creo que no has subido la carpeta docs con la última versión del código, en GitHub Pages no funciona.
- [x] Aquí no hace falta la `key` porque no estamos iterando
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Publica en Github Pages

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by saramarin23** [comment]
Hola Miguel. Sí, me gustaría.
¿Lo hago en la misma rama o saco una nueva?

**Comment by migueldelmazo** [comment]
Hola, súbelo a master directamente, si quieres.

**Comment by saramarin23** [comment]
Subido 👍

**Comment by migueldelmazo** [comment]
Corregido !!! @saramarin23

**Comment by saramarin23** [comment]
Hecho!
Por alguna razón no se ve en pages. He seguido todos los pasos y se sigue mostrando la versión anterior.

**Comment by migueldelmazo** [comment]
Hola, prueba lo siguiente:

1. Borra de tu local las carpetas build y docs
1. Commitea
1. Sustituye en `package.json` la línea https://github.com/Adalab/m3-evaluacion-intermedia-saramarin23/blob/master/package.json#L13 por `"build": "react-scripts build && rm -rf docs && mv build docs",`
1. Haz `npm run build`
1. Commitea
1. Pushea

Y me cuentas!

**Comment by saramarin23** [comment]
Ahora en la página me sale un enlace a pages y el README.

**Comment by migueldelmazo** [comment]
Ya sale bien, había que esperar un poquito!!

**Comment by saramarin23** [comment]
Ahora sí, muchas gracias, Miguel!

**Comment by migueldelmazo** [comment]
Buen trabajo!!!
